### PR TITLE
Add the configuration option [plugin][load_path]

### PR DESCRIPTION
**Pull request by claudyus**
This option can be used to specify absolute and relative paths on which
the bot will looking for additional plugins.

The introduction of this feature will decreare the need for user to fork
this repo just to add some vertical/not-shareble plugins.
You can see some example scouting the repo network:
 https://github.com/1stvamp/hippybot/network

Signed-off-by: Claudio Mignanti <c.mignanti@gmail.com>

### CODE REVIEW

**Comment by 1stvamp** [comment]
@claudyus excellent! Thanks a lot for this.

:cake:

**Comment by claudyus** [comment]
Great @1stvamp thanks for merging this PR.

Can I kindly ask if you could made a minor release on PyPi with this feature?

**Comment by 1stvamp** [comment]
@claudyus done! https://pypi.python.org/pypi/hippybot/1.2.5

**Comment by 1stvamp** [comment]
https://pypi.python.org/pypi/hippybot/1.2.6 even, 1.2.5 had a corrupted tar so removed and republished (thanks pypi for not allowing old re-releases :disappointed:)

**Comment by claudyus** [comment]
Great many thanks! ;)

**Comment by 1stvamp** [comment]
@claudyus I don't really get much oppertunity to work on hippybot any longer, I no longer use hipchat for work etc., would you be happy to be added to the contributors on the repo?

**Comment by claudyus** [comment]
@1stvamp I can image that the in Canonical you are not using Hipchat anymore.

I will be happy to contribute and review any further improvement

**Comment by 1stvamp** [comment]
@claudyus cheers! I've added you.

If you have pypi account I'll add you as a maintainer on there so you can make releases too.

**Comment by claudyus** [comment]
Yes please, I have a pypi account with the same nickname.

cheers!!

**Pull request merged**
